name: deploy to labiej.github.io

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # Download hugo source files
      - uses: actions/checkout@v2
        with:
          submodules: true # Include the theme
          fetch-depth: 0

      # Set-up hugo for use in github actions
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      # Run hugo and update the site
      - name: Build site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use a deploy key, this gives fine-grained control over which actions
          # can push to which repository
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # push into a separate repository
          # this keeps the source and the artifacts separate
          external_repository: labiej/labiej.github.io
          # the branch to use on the external repository
          publish_branch: master
           # The location of the generated website (in the virtual environment)
          publish_dir: ./public
          # Do not use force_orphan for now, this destroys all history
          # Perhaps this should be done in the future to make it clear the target repository
          # is generated, I haven't made up my mind yet.
